name: Push
on:
  pull_request:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
          check-latest: true

      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build Go code
        run: task build

#      - name: Lint Go code
#        run: task lint

      - name: Test Go code
        run: task test